services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3012:3012"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://192.168.0.94:3102
      - BACKEND_URL=http://192.168.0.94:3102
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - workplan-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3102:3102"
    environment:
      - NODE_ENV=production
      - DB_HOST=192.168.0.94
      - DB_USER=jitdhana
      - DB_PASSWORD=iT12345$
      - DB_NAME=esp_tracker
      - DB_PORT=3306
    restart: unless-stopped
    networks:
      - workplan-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  workplan-network:
    driver: bridge
