version: '3.8'

services:
  frontend:
    image: itjitdhana/workplnav6.2:latest
    ports:
      - "3011:3011"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:3011
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3012:3011"
    environment:
      - NODE_ENV=production
      - DB_HOST=192.168.0.94
      - DB_USER=jitdhana
      - DB_PASSWORD=iT12345$
      - DB_NAME=esp_tracker
      - DB_PORT=3306
    restart: unless-stopped
