services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3011:3011"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3101
      - BACKEND_URL=http://backend:3101
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - workplan-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3101:3101"
    environment:
      - NODE_ENV=development
      - DB_HOST=host.docker.internal
      - DB_USER=jitdhana
      - DB_PASSWORD=iT12345$
      - DB_NAME=esp_tracker
      - DB_PORT=3306
    restart: unless-stopped
    networks:
      - workplan-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  workplan-network:
    driver: bridge
