services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3011:3011"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://192.168.0.94:3101
      - BACKEND_URL=http://backend:3101
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - workplan-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3101:3101"
    environment:
      - NODE_ENV=production
      - DB_HOST=192.168.0.94
      - DB_USER=jitdhana
      - DB_PASSWORD=iT12345$
      - DB_NAME=esp_tracker
      - DB_PORT=3306
    restart: unless-stopped
    networks:
      - workplan-network

networks:
  workplan-network:
    driver: bridge
